name: Naver Paper Python GitHub Actions
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get update
        sudo apt-get install -y gdebi-core
        sudo gdebi google-chrome-stable_current_amd64.deb        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        NAVERUSERNAME=$USERNAME1 NAVERPASSWORD=$PASSWORD1 SENDSLACK=False python run_new.py
        NAVERUSERNAME=$USERNAME2 NAVERPASSWORD=$PASSWORD2 SENDSLACK=True python run_new.py
      env:
        USERNAME1: ${{ secrets.ID1 }} # secret에 저장된 내용을 불러옴
        PASSWORD1: ${{ secrets.PASSWORD1 }}
        USERNAME2: ${{ secrets.ID2 }} # secret에 저장된 내용을 불러옴
        PASSWORD2: ${{ secrets.PASSWORD2 }}
        SLACKTOKEN: ${{ secrets.SLACKTOKEN }}
